"""add user profile table

Revision ID: b5c6011a3cd3
Revises: 20260316_0016
Create Date: 2026-03-18 00:11:53.798162
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'b5c6011a3cd3'
down_revision = '20260316_0016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.drop_index(op.f('ix_document_versions_version_number'), table_name='document_versions')
    op.create_foreign_key(None, 'document_versions', 'document_versions', ['supersedes_version_id'], ['id'])
    op.create_foreign_key(None, 'extracted_documents', 'ocr_results', ['current_ocr_result_id'], ['id'])
    op.create_foreign_key(None, 'measurements', 'document_versions', ['document_version_id'], ['id'])
    op.drop_index(op.f('ix_ocr_results_record_file_id_revision_number'), table_name='ocr_results')
    op.create_foreign_key(None, 'ocr_results', 'ocr_results', ['supersedes_ocr_result_id'], ['id'])
    op.alter_column('risk_evaluations', 'document_version_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'risk_evaluations', 'document_versions', ['document_version_id'], ['id'])
    op.create_foreign_key(None, 'risk_evaluations', 'risk_evaluations', ['supersedes_evaluation_id'], ['id'])
    op.create_foreign_key(None, 'risk_evaluations', 'risk_evaluations', ['superseded_by_evaluation_id'], ['id'])
    op.alter_column('risk_results', 'document_version_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'risk_results', 'document_versions', ['document_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risk_results', type_='foreignkey')
    op.alter_column('risk_results', 'document_version_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'risk_evaluations', type_='foreignkey')
    op.drop_constraint(None, 'risk_evaluations', type_='foreignkey')
    op.drop_constraint(None, 'risk_evaluations', type_='foreignkey')
    op.alter_column('risk_evaluations', 'document_version_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'ocr_results', type_='foreignkey')
    op.create_index(op.f('ix_ocr_results_record_file_id_revision_number'), 'ocr_results', ['record_file_id', 'revision_number'], unique=True)
    op.drop_constraint(None, 'measurements', type_='foreignkey')
    op.drop_constraint(None, 'extracted_documents', type_='foreignkey')
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.create_index(op.f('ix_document_versions_version_number'), 'document_versions', ['version_number'], unique=False)
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
