"""add priority and batch_id to tasks

Revision ID: d6f563aaa911
Revises: b5c6011a3cd3
Create Date: 2026-03-18 00:14:00.270533
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd6f563aaa911'
down_revision = 'b5c6011a3cd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('batch_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tasks_batch_id'), 'tasks', ['batch_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_batch_id'), table_name='tasks')
    op.drop_column('tasks', 'batch_id')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
